apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  labels:
    app.kubernetes.io/component: standalone-collector
    app.kubernetes.io/instance: opentelemetry-demo
    app.kubernetes.io/name: opentelemetry-collector
    app.kubernetes.io/version: 0.120.0
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      prometheus:
        config:
          scrape_configs:
          - job_name: 'frontend'
            scrape_interval: 10s
            static_configs:
            - targets: ['frontend:8080']
          - job_name: 'cartservice'
            scrape_interval: 10s
            static_configs:
            - targets: ['cartservice:8080']
          - job_name: 'adservice'
            scrape_interval: 10s
            static_configs:
            - targets: ['adservice:8080']
          - job_name: 'checkoutservice'
            scrape_interval: 10s
            static_configs:
            - targets: ['checkoutservice:8080']
          - job_name: 'productcatalogservice'
            scrape_interval: 10s
            static_configs:
            - targets: ['productcatalogservice:8080']
    
    processors:
      batch:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
    
    exporters:
      prometheus:
        endpoint: "0.0.0.0:8889"
    
    service:
      pipelines:
        metrics:
          receivers: [otlp, prometheus]
          processors: [batch, memory_limiter]
          exporters: [prometheus]

