apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: default
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
            cors:
              allowed_origins:
                - "http://*"
                - "https://*"
      httpcheck/frontend-proxy:
        targets:
          - endpoint: http://${env:FRONTEND_PROXY_ADDR}
      nginx:
        endpoint: http://${env:IMAGE_PROVIDER_HOST}:${env:IMAGE_PROVIDER_PORT}/status
        collection_interval: 10s
      postgresql:
        endpoint: "postgresql:5432"
        username: "root"
        password: "otel"
        collection_interval: 10s
        tls:
          insecure: true
      redis:
        endpoint: "valkey-cart:6379"
        username: "valkey"
        collection_interval: 10s
      hostmetrics:
        scrapers:
          cpu:
            metrics:
              system.cpu.utilization:
                enabled: true
              system.cpu.logical.count:
                enabled: true
          disk:
          load:
          filesystem:
            exclude_mount_points:
              mount_points:
                - /dev/*
                - /proc/*
                - /sys/*
                - /run/k3s/containerd/*
                - /var/lib/docker/*
                - /var/lib/kubelet/*
                - /snap/*
              match_type: regexp
            exclude_fs_types:
              fs_types:
                - autofs
                - binfmt_misc
                - bpf
                - cgroup2
                - configfs
                - debugfs
                - devpts
                - devtmpfs
                - fusectl
                - hugetlbfs
                - iso9660
                - mqueue
                - nsfs
                - overlay
                - proc
                - procfs
                - pstore
                - rpc_pipefs
                - securityfs
                - selinuxfs
                - squashfs
                - sysfs
                - tracefs
              match_type: strict
          memory:
            metrics:
              system.memory.utilization:
                enabled: true
              system.memory.limit:
                enabled: true
          network:
          paging:
            metrics:
              system.paging.usage:
                enabled: true
          processes:
          process:
            mute_process_exe_error: true
            mute_process_io_error: true
            mute_process_user_error: true
      filelog:
        include:
          - /var/log/containers/*.log
        start_at: beginning

    exporters:
      debug:
      otlp:
        endpoint: "jaeger:4317"
        tls:
          insecure: true
      prometheus:
        endpoint: "0.0.0.0:8889"
      opensearch:
        logs_index: otel-logs
        http:
          endpoint: "http://opensearch:9200"
          tls:
            insecure: true

    processors:
      batch:
      memory_limiter:
        check_interval: 5s
        limit_percentage: 80
        spike_limit_percentage: 25
      resourcedetection:
        detectors: [env, docker, system]
      transform:
        error_mode: ignore
        trace_statements:
          - context: span
            statements:
              - replace_pattern(name, "\\?.*", "")
              - replace_match(name, "GET /api/products/*", "GET /api/products/{productId}")

    connectors:
      spanmetrics:

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [resourcedetection, memory_limiter, transform, batch]
          exporters: [otlp, debug, spanmetrics]
        metrics:
          receivers: [httpcheck/frontend-proxy, hostmetrics, nginx, otlp, postgresql, redis, spanmetrics]
          processors: [resourcedetection, memory_limiter, batch]
          exporters: [prometheus, debug]
        logs:
          receivers: [otlp, filelog]
          processors: [resourcedetection, memory_limiter, batch]
          exporters: [opensearch, debug]
      telemetry:
        metrics:
          level: detailed
          readers:
            - periodic:
                interval: 10000
                timeout: 5000
                exporter:
                  otlp:
                    protocol: http/protobuf
                    endpoint: http://0.0.0.0:4318
