apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector-config
  namespace: default
  labels:
    app.kubernetes.io/name: otel-collector-config
    app.kubernetes.io/instance: my-otel-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: otel-collector-config
      app.kubernetes.io/instance: my-otel-demo
      component: standalone-collector
  template:
    metadata:
      annotations:
        prometheus.io/port: "9464"
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/name: otel-collector-config
        app.kubernetes.io/instance: my-otel-demo
        component: standalone-collector
    spec:
      serviceAccountName: otel-collector-config
      containers:
        - name: otel-collector-config
          image: otel/opentelemetry-collector-contrib:0.93.0
          imagePullPolicy: IfNotPresent
          command:
            - /otelcol-contrib
            - --config=/conf/otel-collector-config.yaml
          ports:
            - name: otlp
              containerPort: 4317
            - name: otlp-http
              containerPort: 4318
            - name: prometheus
              containerPort: 9464
            - name: metrics
              containerPort: 8888
            - name: jaeger-grpc
              containerPort: 14250
            - name: jaeger-thrift
              containerPort: 14268
            - name: jaeger-compact
              containerPort: 6831
              protocol: UDP
            - name: zipkin
              containerPort: 9411
          volumeMounts:
            - mountPath: /conf
              name: otel-collector-config-volume
            - name: varlogcontainers
              mountPath: /var/log/containers
              readOnly: true
          env:
            - name: GOMEMLIMIT
              value: "160MiB"
      volumes:
        - name: otel-collector-config-volume
          configMap:
            name: otel-collector-config
            items:
              - key: otel-collector-config.yaml
                path: otel-collector-config.yaml
        - name: varlogcontainers
          hostPath:
            path: /var/log/containers
            type: DirectoryOrCreate
